-- 코드를 입력하세요
SELECT  B.USER_ID, B.NICKNAME, A.AMT
FROM(
        SELECT WRITER_ID, SUM(PRICE) AS AMT
        FROM USED_GOODS_BOARD UGB
        WHERE STATUS = 'DONE'
        GROUP BY WRITER_ID
        HAVING AMT >= 700000
)A
JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
ORDER BY A.AMT