-- 코드를 입력하세요
SELECT MP.MEMBER_NAME
   ,   RR.REVIEW_TEXT
   ,   DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN (SELECT MEMBER_ID
         ,   COUNT(*) AS CNT 
      FROM REST_REVIEW 
      GROUP BY MEMBER_ID
      ORDER BY CNT DESC
      LIMIT 1
     ) CNT
ON RR.MEMBER_ID = CNT.MEMBER_ID
JOIN MEMBER_PROFILE MP
ON MP.MEMBER_ID = CNT.MEMBER_ID
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT